name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Check that the build works/passes on the documented minimum version (1.36.0)
  build_minimum:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Switch to min version
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.36.0
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  # Check that all features work on nightly
  build_nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Switch to nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Install cargo-hack
      run: cargo install cargo-hack
    - name: Run tests (--all-features)
      run: cargo test --all-features
    - name: Check feature combinations
      run: cargo hack check --feature-powerset --no-dev-deps
